// "use client";

// import type { Metadata } from "next";
// import type {ReactNode} from 'react';
// import localFont from "next/font/local";
// import {AuthProvider} from "./contexts/AuthContext";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: ReactNode;
// }>) {
//   return (
//     <AuthProvider>
//       <html lang="en">
      
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//           >
//           {children}
//         </body>
//       </html>
//     </AuthProvider>

//   );
// }
// layout.tsx
"use client";  // This marks the file as a client component

import { ReactNode } from 'react';
import { AuthProvider } from './contexts/AuthContext'; // Ensure the AuthContext is available globally
import './globals.css';  // Your global styles

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <AuthProvider>  {/* Wrap the app in AuthProvider to give all children access to auth context */}
      <html lang="en">
        <body>
          {children}  {/* Render the child pages */}
        </body>
      </html>
    </AuthProvider>
  );
}

